spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
  messages:
    basename: Validations
    encoding: UTF-8
server:
  port: 8081
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
